### ISSUE TITLE
Off_Nadir dataset download from AWS

### ISSUE THREAD

**Issue by manishshah1698** [UNCG-DAISY/BuildingFootprints#1]
@ebgoldstein off-nadir data is free to download but it's requiring an AWS account for it. It's 75GB of data to download, can you look into it?

The link to the space-net webpage for your reference: https://spacenet.ai/off-nadir-building-detection/

**Comment by ebgoldstein** [comment]
ok @manishshah1698, I got the sample data and put it in a Google drive..

**Comment by ebgoldstein** [comment]
ok, its huge... i'm going to try and do it with Azure blob storage, and then we can link to it in Colab via: https://www.tensorflow.org/io/tutorials/azure

**Comment by AjayKrishna76** [comment]
I am closing this issue as I guess we are not using this dataset anymore.
