### ISSUE TITLE
Download XBD dataset

### ISSUE THREAD

**Issue by manishshah1698** [UNCG-DAISY/BuildingFootprints#11]
Download dataset to modify it. The dataset folder is unavailable. Working to recreate combined dataset folder by using datawrangling. ipynb

**Comment by ebgoldstein** [comment]
i think you can close this? - once the `unet_inria_colab` file is working, I think you can test the method directly on the NOAA images, and then we can evaluate how well the method works.

**Comment by manishshah1698** [comment]
Issue closed as getting success in running U-Net model by Dr Mort Canty.

**Comment by manishshah1698** [comment]
Issue closed as getting success in running U-Net model by Dr Mort Canty.
