### ISSUE TITLE
Google Earth Engine(GEE) Asset creation (MortCanty UNET Model)

### ISSUE THREAD

**Issue by manishshah1698** [UNCG-DAISY/BuildingFootprints#17]
(MortCanty UNET Model) Labels and images dataset creation and storage in google drive. Have space and storage complexities. The university account has some project creation issues in the google earth engine and so assets cannot be added and used in the project. Working on the issue

**Comment by ebgoldstein** [comment]
I don;t understand, what are exact problems? do you not have enough space on your google drive? or is it Google earth engine access?

**Comment by manishshah1698** [comment]
> I don;t understand, what are exact problems? do you not have enough space on your google drive? or is it Google earth engine access?

The issue is using my university email account(which has 1 TB space in total); I cannot create a new project or add any existing project. WIthout creating the project I cannot add label images to derive NAIP images as well as labels as mentioned b Dr. Mort Canty in his colab book.

**Comment by manishshah1698** [comment]
Issue resolved with personal google account, Working on training model using downloaded images for 2012, 2015 and 2017 years
