### ISSUE TITLE
Dockerfile implementation

### ISSUE THREAD

**Issue by manishshah1698** [UNCG-DAISY/BuildingFootprints#2]
Error in running dockerfile for [https://github.com/CosmiQ/CosmiQ_SN4_Baseline#docker-container-install-troubleshooting](url). Working on this issue. I am working to implement the same requirements within the main code.

**Comment by ebgoldstein** [comment]
i want to 100% avoid the docker implementation — lets do this w/o docker...and just on google colab, you can pip install rasterio and also install GDAL (just google `GDAL Google Colab`)
