### ISSUE TITLE
Upload updated Dataset

### ISSUE THREAD

**Issue by manishshah1698** [UNCG-DAISY/BuildingFootprints#8]
Upload the modified dataset for XBD into google drive. Dataset is not available on google drive. Need to recreate the dataset

**Comment by ebgoldstein** [comment]
what dataset?

**Comment by manishshah1698** [comment]
> what dataset?

It concerns with XBD dataset. The dataset in google drive was altered by someone, and the folder had been deleted by someone.

**Comment by manishshah1698** [comment]
Issue closed as getting success in running U-Net model by Dr Mort Canty.
