### ISSUE TITLE
Modify NOAA images

### ISSUE THREAD

**Issue by manishshah1698** [UNCG-DAISY/BuildingFootprints#9]
Implement XBD code with NOAA images dataset for Florence hurricane. Update and modify  NOAA images as per the required resolution in XBD model

**Comment by ebgoldstein** [comment]
we can close this right? since we are working with the `unet_inria_colab` method, not the XBD method?

**Comment by manishshah1698** [comment]
Issue closed as getting success in running U-Net model by Dr Mort Canty.
